FROM node:16.1.0-alpine3.11

#Install some dependencies

WORKDIR /home/node/app

# ENTRYPOINT ["docker-node-start.sh"]

#COPY ./application /home/node/app

CMD apk add -q git

ENV NODE_ENV production


USER node

COPY --chown=node:node ./application .

CMD npm i --save-dev laravel-mix@latest
CMD npm i --save-dev sass-loader@latest
CMD npm i --save-dev postcss@latest
CMD npm i --save-dev webpack@latest

RUN npm ci --only=production


# Set up a default command
# CMD [ "npm","start" ]
CMD [ “node”, “npm”]