version: '3' 
services: 
  
  php: 
    container_name: php8_capes
    image: gcsilva/ubuntu20.04-php8.0.3
    ports: 
      - 8081:80
    #tty: true 
    volumes: 
      - ./application:/var/www/html
    depends_on: 
      - db 
      
  db: 
    container_name: mysql8_capes
    image: mysql:8.0.23
    ports: 
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: root 